
Muralla
-------

Framework pre-configurado para la implementación del estandar OAuth 1.0a (http://oauth.net/core/1.0a/) en aplicaciones WEB mediante comunicación REST

=== _Requisitos_

*   JDK 1.7 (o superior)
*   MAVEN 3.x
*   Servidor de aplicaciones JEE6 compatible
*   Aplicación de login que auspicie de proveedor de identidad (*'IDP'*) y aplicación que expone servicios REST segurizados (*'SP'*).

=== _Componentes_

*   _Model_ (*muralla-model*), el cual contiene las clases e interfaces de modelo de datos que se utilizan para enviar/recibir información, como así también algunos utilitarios
*   _Service_ (*muralla-service*), el cual contiene las interfaces de servicios necesarios para el guardado y recuperación de los elementos (tokens, consumers, etc)
*   _Resource_ (*muralla-resource*), el cual contiene los componentes JAX-RS para la obtención y verificación de tokens

==== _Componentes extras_

*   _Model JPA_ (*muralla-model-jpa*), el cual contiene una implementación de gestión de tokens utilizando una base de datos SQL como fuente de datos. Tener en consideración que para utilizar este componente se debe contar con un *persistence.xml* para poder utilizar entidades JPA2.
*   _Service JPA_ (*muralla-service-jpa*), el cual contiene servicios de operaciones con base de datos SQL. Este componente utiliza una unidad de persistencia llamada *'muralla-security-oauth'*

=== _Instalación_

Para comenzar a interactuar y gestionar las autorizaciones mediante la utilización de tokens, es preciso:

*   Descargar el proyecto y compilarlo

    mvn clean install

*   En el *pom.xml* que corresponde a la aplicación '*IDP*' agregar la siguiente dependencia:

	<dependency>
		<groupId>org.security.muralla</groupId>
		<artifactId>muralla-resource-auth</artifactId>
		<version>${muralla.version}</version>
	</dependency>
	
	<!--
	    Opcional
	    Dependencia para utilización de componentes JPA2 (SQL)
	-->
	<dependency>
		<groupId>org.security.muralla</groupId>
		<artifactId>muralla-service-jpa</artifactId>
		<version>${muralla.version}</version>
	</dependency>

*   En el *pom.xml* que corresponde a la aplicación '*SP*' agregar la siguiente dependencia:

	<dependency>
		<groupId>org.security.muralla</groupId>
		<artifactId>muralla-resource-gen</artifactId>
		<version>${muralla.version}</version>
	</dependency>

	<!--
	    Opcional
	    Dependencia para utilización de componentes JPA2 (SQL)
	-->
	<dependency>
		<groupId>org.security.muralla</groupId>
		<artifactId>muralla-service-jpa</artifactId>
		<version>${muralla.version}</version>
	</dependency>

*   Generar los binarios de el/las aplicaciones
*   Desplegar el/los binarios en el contenedor de aplicaciones

=== _Utilización_
